Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${App}-${Env}-${Name}-Table'
      AttributeDefinitions:
        - AttributeName: OutcomeID
          AttributeType: S
      KeySchema:
        - AttributeName: OutcomeID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

# This section tells Copilot to automatically grant permissions
Outputs:
  DynamoDBTableName:
    Value: !Ref MyDynamoDBTable